version: "3.9"

services:
  web:
    build: .
    container_name: nexus-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.aws:/home/myuser/.aws
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:15-alpine
    container_name: nexus_postgres_db
    restart: always
    environment:
      POSTGRES_USER: nexus_user
      POSTGRES_PASSWORD: nexus_password
      POSTGRES_DB: nexus_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge

